#!/usr/bin/zsh

function() {

local hostname='0.0.0.0'

local tabs_url='http''://'"${hostname}"':'"${remote_debug_port}"'/json'

urls=$(noglob curl -sg "${tabs_url}" | underscore pluck url --outfmt text | grep -e 'dharmatreasure')

# TODO: Grab page urls and add everything found there to the list of urls to 
# check (i.e., recursively find urls)

IFS=$'\n' urls=($(sort <<< "${urls}"))
IFS=$'\n' urls+=($(</home/chris/pages))

for url in "${urls[@]}"; do

  echo 'url: ' $url

  local magnet=$(noglob curl --silent -g "${url}" -H 'Pragma: no-cache' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: en-US,en;q=0.8' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.82 Safari/537.36' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Cookie: wordpress_logged_in_03d3d63b5f1a62ad846d7daddb3f21ed=s00pcan%7C1454686782%7Cnkp95gZkfqSGVj8dgiyFeqOtCSb3e6vACRpdVBve8ak%7C20a0c534d14a3fd07857468b9df37d71b03160c592248020167869cf2f8f8038' -H 'Connection: keep-alive' -H 'Cache-Control: no-cache' --compressed | grep -oP "(?<=href=\")[^\"]+(?=\")" | grep '\.mp3' | sort -u)

  if [[ -z $magnet ]]; then
    continue
  fi

  echo $magnet

  echo "${magnet}" >> /home/chris/links

  sort -uo /home/chris/links /home/chris/links

done

}

