#!/bin/sh

export DISPLAY=:0

HDTV=$(xrandr -q | grep -e 'HDMI1 connected')
DP1=$(xrandr -q | grep -e '^DP1 connected')
eDP1=$(xrandr -q | grep -e 'eDP1 connected')

# if [[ ! -z "$HDTV" ]]; then
#   /usr/bin/xrandr --output 'eDP1' --auto --output 'HDMI1' --right-of 'eDP1' --auto
# fi

if [[ ! -z "$DP1" ]]; then
  # /usr/bin/xrandr --output 'eDP1' --auto --output 'DP1' --right-of 'eDP1' --auto --rotate left
  # /usr/bin/xrandr --output 'eDP1' --off --output 'DP1' --right-of 'eDP1' --auto --rotate normal
  /usr/bin/xrandr --output 'eDP1' --off
  /usr/bin/xrandr --output 'DP1' --auto --rotate normal
else
  /usr/bin/xrandr --output 'DP1' --off 
  /usr/bin/xrandr --output 'eDP1' --auto --rotate normal
fi

# if [[ -z "${DP1}${HDTV}" ]]; then
#   /usr/bin/xrandr --output 'eDP1' --auto --output 'HDMI1' --off --output 'DP1' --off
# fi

# TODO: Move these to a keyboard related rule
xmodmap /home/chris/.xmodmap
xset r rate 200 90

