#!/bin/sh

/usr/local/bin/redis-cli set "add" "awesome"
export DISPLAY=:0

/usr/bin/xrandr --output 'DisplayPort-0' --auto --rotate normal --left-of 'DVI-0' --output 'HDMI-0' --auto --rotate left --left-of 'DisplayPort-0' --output 'DVI-0' --auto --rotate left

